name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: actions

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create env file
      run: |
        cd oj/oj
        touch .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "SQL_DEV_DB_NAME=${{ secrets.SQL_DEV_DB_NAME }}" >> .env
        echo "SQL_DEV_DB_USERNAME=${{ secrets.SQL_DEV_DB_USERNAME }}" >> .env
        echo "SQL_DEV_DB_PASSWORD=${{ secrets.SQL_DEV_DB_PASSWORD }}" >> .env
        echo "SQL_TEST_DB_NAME=${{ secrets.SQL_TEST_DB_NAME }}" >> .env
        echo "SQL_TEST_DB_USERNAME=${{ secrets.SQL_TEST_DB_USERNAME }}" >> .env
        echo "SQL_TEST_DB_PASSWORD=${{ secrets.SQL_TEST_DB_PASSWORD }}" >> .env
        echo "SQL_SERVER_HOST=${{ secrets.SQL_SERVER_HOST }}" >> .env
        echo "SQL_PORT=${{ secrets.SQL_PORT }}" >> .env
        echo "HDU_ACCOUNT=${{ secrets.HDU_ACCOUNT }}" >> .env
        echo "HDU_PASSWORD=${{ secrets.HDU_PASSWORD }}" >> .env
        echo "REDIS_LOCATION=${{ secrets.REDIS_LOCATION }}" >> .env
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
        cd ../..
        pwd
    - name: Run Tests
      run: |
        cd oj
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
