name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    environment: actions

    runs-on: ubuntu-latest
    # runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up SSH config
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.JUDGE_SERVER_HOST }} >> ~/.ssh/known_hosts
    - name: Test rsync connection over SSH
      run: |
        rsync -r README.md root@${{ secrets.JUDGE_SERVER_HOST }}:/www/bar/
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create env file
      run: |
        cd oj/oj
        touch .env
        echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env
        echo 'SQL_DEV_DB_NAME=${{ secrets.SQL_DEV_DB_NAME }}' >> .env
        echo 'SQL_DEV_DB_USERNAME=${{ secrets.SQL_DEV_DB_USERNAME }}' >> .env
        echo 'SQL_DEV_DB_PASSWORD=${{ secrets.SQL_DEV_DB_PASSWORD }}' >> .env
        echo 'SQL_TEST_DB_NAME=${{ secrets.SQL_TEST_DB_NAME }}' >> .env
        echo 'SQL_TEST_DB_USERNAME=${{ secrets.SQL_TEST_DB_USERNAME }}' >> .env
        echo 'SQL_TEST_DB_PASSWORD=${{ secrets.SQL_TEST_DB_PASSWORD }}' >> .env
        echo 'SQL_SERVER_HOST=${{ secrets.SQL_SERVER_HOST }}' >> .env
        echo 'SQL_PORT=${{ secrets.SQL_PORT }}' >> .env
        echo 'HDU_ACCOUNT=${{ secrets.HDU_ACCOUNT }}' >> .env
        echo 'HDU_PASSWORD=${{ secrets.HDU_PASSWORD }}' >> .env
        echo 'REDIS_HOST=${{ secrets.REDIS_HOST }}' >> .env
        echo 'REDIS_PORT=${{ secrets.REDIS_PORT }}' >> .env
        echo 'REDIS_LOCATION=${{ secrets.REDIS_LOCATION }}' >> .env
        echo 'REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}' >> .env
        echo 'JUDGE_SERVER_TOKEN=${{ secrets.JUDGE_SERVER_TOKEN }}' >> .env
        echo 'JUDGE_SERVER_HOST=${{ secrets.JUDGE_SERVER_HOST }}' >> .env
        echo 'JUDGE_SERVER_PORT=${{ secrets.JUDGE_SERVER_PORT }}' >> .env
        echo 'JUDGE_SERVER_USER=${{ secrets.JUDGE_SERVER_USER }}' >> .env
        echo 'TEST_CASE_DIR=${{ secrets.TEST_CASE_DIR }}' >> .env
        echo 'JUDGE_SERVER_TEST_CASE_DIR=${{ secrets.JUDGE_SERVER_TEST_CASE_DIR }}' >> .env
        cd ../..
        pwd
    - name: Run Tests
      run: |
        cd oj
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test --noinput --settings=oj.settings_test
